/* Copyright 2025 The xLLM Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://github.com/jd-opensource/xllm-service/blob/main/LICENSE

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

#pragma once

#include <absl/time/time.h>

#include "chat_template/jinja_chat_template.h"
#include "common/call_data.h"
#include "common/types.h"
#include "common/xllm/output.h"

namespace xllm_service {

struct StageTimingTrace {
  int64_t ingress_ts_ms = 0;
  int64_t route_decision_ts_ms = 0;
  int64_t prefill_dispatch_ts_ms = 0;
  int64_t first_prefill_callback_ts_ms = 0;
  int64_t first_decode_callback_ts_ms = 0;
  int64_t finish_ts_ms = 0;
  int64_t worker_prefill_ingress_ts_ms = 0;
  int64_t worker_prefill_first_token_ts_ms = 0;
  int64_t worker_prefill_output_emit_ts_ms = 0;
  int64_t worker_decode_ingress_ts_ms = 0;
  int64_t worker_decode_first_token_ts_ms = 0;
  int64_t worker_decode_output_emit_ts_ms = 0;
  int64_t decode_admission_wait_ms = 0;
  int32_t decode_admission_attempts = 0;
  int64_t decode_admission_active_requests = -1;
  int64_t decode_admission_waiting_requests = -1;
  int64_t decode_admission_estimated_tpot_ms = -1;
  std::string decode_admission_pressure_tier;
  std::string decode_admission_preferred_decode_instance;
  bool decode_admission_preferred_decode_matched = false;
  bool dynamic_cp_shadow_enabled = false;
  bool dynamic_cp_takeover_enabled = false;
  bool dynamic_cp_decode_takeover_enabled = false;
  bool dynamic_cp_takeover_applied_prefill = false;
  bool dynamic_cp_takeover_applied_decode = false;
  std::string dynamic_cp_shadow_selected_prefill_instance;
  std::string dynamic_cp_shadow_selected_decode_instance;
  std::string dynamic_cp_shadow_selected_lane_type;
  double dynamic_cp_shadow_selected_cost = 0.0;
  double dynamic_cp_shadow_selected_prefill_cost = 0.0;
  double dynamic_cp_shadow_selected_decode_pressure_cost = 0.0;
  double dynamic_cp_shadow_selected_cp_benefit = 0.0;
  double dynamic_cp_shadow_selected_interference_cost = 0.0;
  bool dynamic_cp_shadow_would_change_prefill = false;
  bool dynamic_cp_shadow_would_change_decode = false;
  bool warmup_triggered = false;
  std::string warmup_state;
  std::string warmup_reason;
  int64_t worker_idle_ms = -1;
  int32_t pending_requests = 0;
  int32_t running_requests = 0;
  std::string skip_reason;
};

// Store request-related data
struct Request {
  // model name
  std::string model;

  // request id generated by service
  std::string service_request_id;

  // request id propagated from the client, typically via x-request-id
  std::string client_request_id;

  // whether to stream the response
  bool stream = false;

  // whether to return usage
  bool include_usage = false;

  // requested generation budget, if provided by the client
  int64_t max_tokens = 0;

  bool offline = false;

  // input prompt
  std::string prompt;

  // input messages
  ChatMessages messages;

  // tool definitions for function/tool calling
  std::vector<JsonTool> tools;

  // controls tool usage behavior, e.g. auto/none/required
  std::string tool_choice = "auto";

  // extra template context such as {"enable_thinking": false}
  nlohmann::json chat_template_kwargs = nlohmann::json::object();

  // token ids of prompt
  std::vector<int32_t> token_ids;

  // instance routing
  Routing routing;
  std::string prefill_incarnation_id;
  std::string decode_incarnation_id;

  // prefill stage finished
  bool prefill_stage_finished = false;

  // the number of generated tokens
  int64_t num_generated_tokens = 0;

  // the estimated TTFT obtained from the TTFT predictor
  int64_t estimated_ttft = 0;

  // output callback
  OutputCallback output_callback;

  std::shared_ptr<CallData> call_data;

  // trace callback
  std::function<void(const std::string&)> trace_callback = nullptr;

  // latest token generate time
  absl::Time latest_generate_time;

  // request lifecycle timing split for stage trace
  StageTimingTrace stage_timing_trace;
};

}  // namespace xllm_service
