/* Copyright 2025 The xLLM Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://github.com/jd-opensource/xllm-service/blob/main/LICENSE

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

#pragma once

#include <gflags/gflags.h>

DECLARE_string(server_host);

DECLARE_int32(http_server_port);

DECLARE_int32(http_server_idle_timeout_s);

DECLARE_int32(http_server_num_threads);

DECLARE_int32(http_server_max_concurrency);

DECLARE_int32(rpc_server_port);

DECLARE_int32(rpc_server_idle_timeout_s);

DECLARE_int32(rpc_server_num_threads);

DECLARE_int32(rpc_server_max_concurrency);

DECLARE_uint32(xxh3_128bits_seed);

DECLARE_int32(timeout_ms);

DECLARE_int32(connect_timeout_ms);

DECLARE_string(listen_addr);

DECLARE_int32(port);

DECLARE_int32(idle_timeout_s);

DECLARE_int32(num_threads);

DECLARE_int32(max_concurrency);

DECLARE_string(etcd_addr);

DECLARE_string(etcd_namespace);

DECLARE_string(load_balance_policy);
DECLARE_bool(enable_static_prefill_instance_split);
DECLARE_string(static_prefill_short_instance_selectors);
DECLARE_string(static_prefill_long_instance_selectors);
DECLARE_bool(enable_static_prefill_soft_fallback);
DECLARE_int32(static_prefill_soft_fallback_request_num_gap);
DECLARE_int32(static_prefill_soft_fallback_token_gap);
DECLARE_bool(enable_static_prefill_load_aware_tie_break);
DECLARE_bool(enable_hybrid_prefill_affinity_routing);
DECLARE_double(hybrid_prefill_long_affinity_bonus);
DECLARE_double(hybrid_prefill_short_affinity_bonus);
DECLARE_bool(hybrid_prefill_dynamic_long_affinity_gain_enabled);
DECLARE_double(hybrid_prefill_long_affinity_base_bonus);
DECLARE_double(hybrid_prefill_long_affinity_dynamic_bonus_max);
DECLARE_int32(hybrid_prefill_dynamic_load_gain_window);
DECLARE_int32(hybrid_prefill_dynamic_projected_prefill_time_margin_ms);
DECLARE_double(hybrid_prefill_request_num_weight);
DECLARE_double(hybrid_prefill_waiting_requests_weight);
DECLARE_double(hybrid_prefill_token_num_weight);
DECLARE_int32(hybrid_prefill_overload_threshold);
DECLARE_double(hybrid_prefill_rescue_bonus);
DECLARE_int32(hybrid_prefill_rescue_min_tokens);
DECLARE_int32(hybrid_prefill_rescue_max_tokens);
DECLARE_int32(hybrid_prefill_rescue_load_gap);
DECLARE_bool(enable_hybrid_prefill_short_long_lane_guard);
DECLARE_bool(hybrid_prefill_short_long_lane_guard_hard_reject);
DECLARE_int32(hybrid_prefill_short_long_lane_guard_window_ms);
DECLARE_int32(hybrid_prefill_short_long_lane_guard_request_count);
DECLARE_int32(hybrid_prefill_short_long_lane_guard_max_long_lane_combined_load);
DECLARE_int32(hybrid_prefill_short_long_lane_guard_primary_min_load_threshold);
DECLARE_int32(hybrid_prefill_short_long_lane_guard_max_prompt_tokens);
DECLARE_int32(hybrid_prefill_short_long_lane_guard_max_consecutive_borrows);
DECLARE_double(hybrid_prefill_short_long_lane_penalty);
DECLARE_bool(enable_hybrid_prefill_long_short_pool_busy_surcharge);
DECLARE_int32(hybrid_prefill_long_short_pool_busy_combined_load_threshold);
DECLARE_double(hybrid_prefill_long_short_pool_busy_surcharge);
DECLARE_bool(enable_hybrid_prefill_long_short_pool_continuous_surcharge);
DECLARE_double(hybrid_prefill_long_short_pool_busy_surcharge_alpha);
DECLARE_bool(enable_hybrid_prefill_long_short_pool_affine_gap_penalty);
DECLARE_int32(hybrid_prefill_long_short_pool_affine_gap_threshold);
DECLARE_double(hybrid_prefill_long_short_pool_affine_gap_penalty);
DECLARE_string(hybrid_prefill_scoring_version);
DECLARE_int32(hybrid_prefill_v0_3_soft_long_lower_tokens);
DECLARE_int32(hybrid_prefill_v0_3_soft_long_upper_tokens);
DECLARE_double(hybrid_prefill_v0_3b_boundary_long_projected_token_penalty_scale);
DECLARE_double(hybrid_prefill_v0_3c_boundary_long_escape_bonus);
DECLARE_int32(hybrid_prefill_v0_3c_boundary_long_escape_load_gap);
DECLARE_int32(hybrid_prefill_v0_3c_boundary_long_escape_min_affine_load);
DECLARE_bool(enable_hybrid_prefill_long_affine_busy_admission);
DECLARE_int32(hybrid_prefill_long_affine_busy_combined_load_threshold);
DECLARE_double(hybrid_prefill_long_affine_busy_penalty);
DECLARE_bool(enable_prefill_time_route_signal);
DECLARE_double(prefill_time_route_weight);
DECLARE_bool(enable_lane_specific_projected_prefill_time_route_signal);
DECLARE_double(hybrid_prefill_long_lane_projected_prefill_time_weight);
DECLARE_double(hybrid_prefill_short_pool_projected_prefill_time_weight);
DECLARE_bool(enable_lane_normalized_projected_prefill_time_route_signal);
DECLARE_double(hybrid_prefill_long_lane_projected_prefill_time_baseline_ms);
DECLARE_double(hybrid_prefill_short_pool_projected_prefill_time_baseline_ms);
DECLARE_double(hybrid_prefill_projected_prefill_time_normalized_weight);
DECLARE_double(hybrid_prefill_projected_prefill_time_normalized_cap);
DECLARE_double(long_request_token_cost_multiplier);
DECLARE_bool(dynamic_long_request_token_cost_enabled);
DECLARE_double(dynamic_long_request_token_cost_extra_max);
DECLARE_int32(dynamic_long_request_token_cost_overload_threshold);
DECLARE_int32(dynamic_long_request_token_cost_load_gain_window);

DECLARE_int32(detect_disconnected_instance_interval);

DECLARE_int32(instance_delete_probe_timeout_ms);

DECLARE_int32(instance_delete_probe_attempts);

DECLARE_int32(lease_lost_heartbeat_timeout_ms);

DECLARE_int32(block_size);

DECLARE_string(tokenizer_path);

DECLARE_bool(enable_request_trace);
DECLARE_bool(enable_route_trace);
DECLARE_string(route_trace_log_path);
DECLARE_int32(route_trace_sample_every_n);
DECLARE_bool(route_trace_long_requests_only);
DECLARE_bool(enable_dynamic_cp_pricing_shadow);
DECLARE_bool(enable_dynamic_cp_pricing_takeover);
DECLARE_bool(enable_dynamic_cp_pricing_decode_takeover);
DECLARE_double(dynamic_cp_pricing_prefill_time_weight);
DECLARE_double(dynamic_cp_pricing_token_weight);
DECLARE_double(dynamic_cp_pricing_active_weight);
DECLARE_double(dynamic_cp_pricing_waiting_weight);
DECLARE_double(dynamic_cp_pricing_decode_tpot_weight);
DECLARE_double(dynamic_cp_pricing_cp_benefit_weight);
DECLARE_double(dynamic_cp_pricing_interference_weight);
DECLARE_bool(enable_stage_timing_trace);
DECLARE_string(stage_timing_trace_log_path);
DECLARE_int32(long_request_threshold_tokens);

DECLARE_bool(enable_decode_pressure_admission_control);
DECLARE_bool(enable_decode_pressure_soft_signal_only);
DECLARE_int32(decode_pressure_admission_max_active_requests);
DECLARE_bool(decode_pressure_admission_use_estimated_tpot);
DECLARE_int32(decode_pressure_admission_target_tpot_ms);
DECLARE_bool(decode_pressure_admission_use_output_work);
DECLARE_int32(decode_pressure_admission_default_short_output_tokens);
DECLARE_int32(decode_pressure_admission_default_long_output_tokens);
DECLARE_int32(decode_pressure_admission_long_rescue_wait_ms);
DECLARE_int32(decode_pressure_admission_medium_waiting_requests);
DECLARE_int32(decode_pressure_admission_hard_waiting_requests);
DECLARE_int32(decode_pressure_admission_short_active_burst);
DECLARE_int32(decode_pressure_admission_hard_active_burst);
DECLARE_double(decode_pressure_admission_soft_tpot_ratio);
DECLARE_double(decode_pressure_admission_hard_tpot_ratio);
DECLARE_int32(decode_pressure_admission_check_interval_ms);
DECLARE_int32(decode_pressure_admission_timeout_ms);
DECLARE_int32(decode_pressure_admission_log_every_n);
DECLARE_bool(enable_decode_pressure_route_score);
DECLARE_double(decode_pressure_route_score_weight);
DECLARE_double(decode_pressure_route_active_weight);
DECLARE_double(decode_pressure_route_waiting_weight);
DECLARE_double(decode_pressure_route_estimated_tpot_weight);
DECLARE_int32(decode_pressure_route_prefill_delay_decay_ms);
DECLARE_double(decode_pressure_route_long_aging_credit_weight);
DECLARE_double(decode_pressure_route_long_aging_credit_cap);

DECLARE_int32(target_ttft);

DECLARE_int32(target_tpot);

DECLARE_string(tool_call_parser);

DECLARE_string(reasoning_parser);

DECLARE_int32(readiness_check_interval_s);

// Pool elasticity controller flags.
DECLARE_string(pool_elastic_idle_default_instances);
DECLARE_double(pool_elastic_activate_long_ratio);
DECLARE_int32(pool_elastic_activate_min_load);
DECLARE_double(pool_elastic_deactivate_long_ratio);
DECLARE_int32(pool_elastic_deactivate_persist_s);
DECLARE_int32(pool_elastic_drain_timeout_ms);
DECLARE_int32(pool_elastic_window_s);
